/**
 * App build fingerprint -- generated by tools/sync_www.py and tools/build_pages_site.py.
 * Changes whenever deployed runtime assets change, so the service worker cache refreshes
 * without requiring a manual APP_VERSION bump for every small UI fix.
 */
(function (g) {
  'use strict';
  g.APP_BUILD_ID = '26d633a54e1a';
})(typeof self !== 'undefined' ? self : globalThis);
