(function(){
'use strict';
const KEY='seabirds_state_v1';
if(window.__TAURI__?.core?.invoke&&!window.SeaBirdsDesktop)window.SeaBirdsDesktop={saveJson:(filename,data)=>window.__TAURI__.core.invoke('save_json',{filename,data})};
window.units='metric';
window._lspCssVar=(name,fallback)=>getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback;
const sampleProfile=(depth,duration)=>[{t:0,depth:0,type:'surface'},{t:2,depth,type:'descent'},{t:Math.max(3,duration-5),depth,type:'bottom'},{t:duration-2,depth:5,type:'ascent'},{t:duration,depth:0,type:'surface'}];
const demo=[
 {id:'demo-1',date:'2026-07-28',site:'Blue Corner',location:'Palau',depth:31.8,duration:52,temp:28,buddy:'Maya',notes:'Strong current, grey reef sharks.',profile:sampleProfile(31.8,52),updatedAt:new Date().toISOString()},
 {id:'demo-2',date:'2026-07-26',site:'German Channel',location:'Palau',depth:24.3,duration:61,temp:28,buddy:'Maya',notes:'Manta cleaning station.',profile:sampleProfile(24.3,61),updatedAt:new Date().toISOString()},
 {id:'demo-3',date:'2026-06-15',site:'USS Liberty',location:'Tulamben, Bali',depth:27.1,duration:48,temp:27,buddy:'Ken',notes:'Early morning wreck dive.',profile:sampleProfile(27.1,48),updatedAt:new Date().toISOString()}];
const gearCatalog={
 'Core Dive Gear':['BCD / wing','Regulator','Fins','Mask','Wetsuit / Drysuit','Weights & belt','Dive computer','Backup computer'],
 'Safety & Accessories':['SMB + spool','Backup SMB','Torch','Backup torch','Knife / cutter','Wet notes'],
 'Tanks & Gas':['Cylinder(s)','Stage / deco bottles','O2 analyzer'],
 'Camera & Photo':['Camera housing','Camera body','Strobes','Video lights']
};
const defaultGearLibrary=()=>JSON.parse(JSON.stringify(gearCatalog));
let state=load();
let activeDiveId=null;
function load(){try{return Object.assign({dives:[],deletedDiveIds:[],gearLibrary:defaultGearLibrary(),settings:{depth:'m',temp:'c'},revision:0,updatedAt:''},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {dives:[],deletedDiveIds:[],gearLibrary:defaultGearLibrary(),settings:{depth:'m',temp:'c'},revision:0,updatedAt:''}}}
function storeState(sync=true){state.updatedAt=new Date().toISOString();state.revision=(state.revision||0)+1;localStorage.setItem(KEY,JSON.stringify(state));if(sync&&window.SeaBirdsSync)window.SeaBirdsSync.queue(state)}
function persist(sync=true){storeState(sync);render()}
function esc(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML}
function converted(d){return state.settings.depth==='ft'?(d*3.28084):d}
function temp(t){return state.settings.temp==='f'?(t*9/5+32):t}
function formatGas(gas){const [o2,he]=String(gas).split('/').map(Number);if(o2===21&&!he)return'Air';if(!he&&o2>21)return`EAN${o2}`;if(o2&&he)return`Tx ${o2}/${he}`;return gas}
function fmtDate(s){const d=new Date(s+'T12:00:00');return {day:d.getDate(),month:d.toLocaleDateString(undefined,{month:'short'}).toUpperCase(),ymd:`${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')}`,full:d.toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})}}
function rows(target,dives){target.innerHTML=dives.length?dives.map(d=>{const x=fmtDate(d.date),subtitle=d.location||d.buddy||'';return `<button class="dive-row" data-id="${esc(d.id)}"><span class="date-tile full-date"><b>${x.ymd}</b></span><span class="site"><b>${esc(d.site)}</b>${subtitle?`<small>${esc(subtitle)}</small>`:''}</span><span class="metric"><b>${converted(+d.depth).toFixed(1)} ${state.settings.depth}</b></span><span class="metric"><b>${d.duration} min</b></span><span class="metric"><b>${d.temp==null?'—':temp(+d.temp).toFixed(0)+'°'+state.settings.temp.toUpperCase()}</b></span><span>›</span></button>`}).join(''):`<div class="empty"><b>No dives yet</b>Connect your Shearwater or add a dive manually.</div>`}
function render(){
 const dives=[...state.dives].sort((a,b)=>b.date.localeCompare(a.date));
 document.getElementById('diveCount').textContent=dives.length;document.getElementById('statDives').textContent=dives.length;
 const mins=dives.reduce((n,d)=>n+(+d.duration||0),0);document.getElementById('statTime').innerHTML=(mins/60).toFixed(mins>=600?0:1)+'<sup>h</sup>';
 const md=Math.max(0,...dives.map(d=>+d.depth||0));document.getElementById('statDepth').textContent=dives.length?converted(md).toFixed(1)+' '+state.settings.depth:'—';
 const longest=Math.max(0,...dives.map(d=>+d.duration||0)),longestMinutes=Math.round(longest),longestHours=Math.floor(longestMinutes/60),longestRemainder=longestMinutes%60;document.getElementById('statLongest').textContent=dives.length?(longestHours?`${longestHours}h ${longestRemainder}min`:`${longestRemainder}min`):'—';
 rows(document.getElementById('recentDives'),dives.slice(0,4));filterRows();
 document.getElementById('depthUnit').value=state.settings.depth;document.getElementById('tempUnit').value=state.settings.temp;
}
function filterRows(){let ds=[...state.dives],q=(document.getElementById('search').value||'').toLowerCase(),sort=document.getElementById('sort').value;if(q)ds=ds.filter(d=>JSON.stringify(d).toLowerCase().includes(q));ds.sort(sort==='date-asc'?(a,b)=>a.date.localeCompare(b.date):sort==='depth-desc'?(a,b)=>b.depth-a.depth:(a,b)=>b.date.localeCompare(a.date));rows(document.getElementById('allDives'),ds)}
function go(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===id));document.getElementById('viewName').textContent=({dashboard:'Overview',dives:'Dive log',devices:'Devices',settings:'Settings'})[id];document.querySelector('.sidebar').classList.remove('open')}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function renderDiveEquipment(d){
 const defaults=defaultGearLibrary(),library={...defaults,...(state.gearLibrary||{})},categoryMap=d.equipmentCategories||{},uncategorized=(d.equipment||[]).some(name=>!categoryMap[name]&&!Object.keys(library).some(category=>(library[category]||[]).includes(name))),categories=[...new Set([...Object.keys(defaults),...Object.keys(library),...(uncategorized?['Custom']:[])])];
 const used=(d.equipment||[]).map(name=>({name,category:categoryMap[name]||Object.keys(library).find(category=>(library[category]||[]).includes(name))||'Custom'}));
 document.getElementById('diveEquipment').innerHTML=`<div class="gear-toolbar"><button type="button" id="addGearCategory">+ Add card</button></div>${categories.map(category=>{const items=used.filter(item=>item.category===category),custom=!Object.prototype.hasOwnProperty.call(defaults,category);return `<div class="gear-category" data-category="${esc(category)}"><header><h3>${esc(category)}</h3><span><button type="button" class="add-gear-to-category" data-category="${esc(category)}" title="Add equipment" aria-label="Add equipment to ${esc(category)}">+</button>${custom?`<button type="button" class="rename-gear-category" data-category="${esc(category)}" title="Rename card" aria-label="Rename ${esc(category)} card">✎</button><button type="button" class="remove-gear-category" data-category="${esc(category)}" title="Remove card" aria-label="Remove ${esc(category)} card">×</button>`:''}</span></header><div class="gear-card-items">${items.length?items.map(item=>`<div class="gear-item"><span>${esc(item.name)}</span><button type="button" class="rename-gear" data-item="${esc(item.name)}" title="Rename equipment" aria-label="Rename ${esc(item.name)}">✎</button><button type="button" class="remove-dive-gear" data-item="${esc(item.name)}" title="Remove from this dive" aria-label="Remove ${esc(item.name)} from this dive">×</button></div>`).join(''):`<small>No equipment added</small>`}</div></div>`}).join('')}`;
}
function saveDiveEquipment(d,message){d.userEdited=true;d.updatedAt=new Date().toISOString();storeState();renderDiveEquipment(d);toast(message)}
function openProfile(id){
 const d=state.dives.find(x=>x.id===id);if(!d)return;activeDiveId=id;
 document.getElementById('profileTitle').textContent=d.site+' · '+fmtDate(d.date).full;
 const profile=d.profile?.length?d.profile.map(p=>({...p,t:p.t??p.time})):sampleProfile(+d.depth,+d.duration),temps=profile.map(p=>p.temperature??p.temp).filter(Number.isFinite),tts=profile.map(p=>p.tts).filter(Number.isFinite),rawGases=[...new Set([...(d.gases||[]),...profile.map(p=>p.gas).filter(Boolean)])],gases=rawGases.map(formatGas),cns=profile.map(p=>p.cns).filter(Number.isFinite),hasTelemetry=profile.some(p=>p.ndl!=null||p.tts!=null||p.gas);
 document.getElementById('telemetryNotice').hidden=hasTelemetry||!String(d.id).startsWith('shearwater-');
 const headerDepths=profile.map(p=>+p.depth).filter(Number.isFinite),headerAverage=d.avgDepth||(headerDepths.length?headerDepths.reduce((a,b)=>a+b,0)/headerDepths.length:0),headerTemp=temps.length?temp(Math.min(...temps)).toFixed(1)+'°'+state.settings.temp.toUpperCase():d.temp!=null?temp(+d.temp).toFixed(1)+'°'+state.settings.temp.toUpperCase():null,headerAverageTemp=temps.length?temp(temps.reduce((a,b)=>a+b,0)/temps.length).toFixed(1)+'°'+state.settings.temp.toUpperCase():d.temp!=null?temp(+d.temp).toFixed(1)+'°'+state.settings.temp.toUpperCase():null,headerGas=gases.length?gases.join(' · '):profile.some(p=>p.setpoint!=null)?null:'Air',headerMode=profile.some(p=>p.setpoint!=null)?'CCR / SCR':'Open circuit',headerStats=[['Dive date',fmtDate(d.date).full],['Dive mode',headerMode],['Maximum depth',converted(+d.depth).toFixed(1)+' '+state.settings.depth],['Dive time',d.duration+' min'],['Minimum water temp',headerTemp],['Average temperature',headerAverageTemp],['Mean Depth',headerAverage?converted(headerAverage).toFixed(1)+' '+state.settings.depth:null],['Maximum TTS',tts.length?Math.max(...tts)+' min':null],['Maximum CNS',cns.length?Math.max(...cns)+'%':null],['Gas used (Perdix)',headerGas],['Device GF',d.gfLow!=null?d.gfLow+'/'+d.gfHigh:null]].filter(x=>x[1]!=null);document.getElementById('profileStats').innerHTML=headerStats.map(([label,value])=>`<span><b>${esc(value)}</b>${esc(label)}</span>`).join('');
 document.getElementById('editDiveTitle').value=d.site||'';const spot=document.getElementById('editDiveSpot'),notes=document.getElementById('editDiveNotes');spot.placeholder='Enter dive spot location';notes.placeholder='Enter dive notes';spot.value=d.location==='Downloaded from Shearwater'?'':d.location||'';document.getElementById('editDiveBuddy').value=d.buddy||'';document.getElementById('editDiveTags').value=(d.tags||[]).join(', ');notes.value=d.notes==='Downloaded from Perdix'?'':d.notes||'';
 renderDiveEquipment(d);
 const isComputerDive=String(d.id).startsWith('shearwater-'),serialFallback=isComputerDive?String(d.id).split('-')[1]:null,computerInfo=[['Model',d.computer||'Shearwater Perdix'],['Serial',d.computerSerial||serialFallback||'—'],['Firmware',d.computerFirmware||'Refresh from computer'],['Log version',d.logVersion!=null?d.logVersion+' (PNF)':'Refresh from computer'],['Decompression model',d.gfLow!=null?`Bühlmann GF ${d.gfLow}/${d.gfHigh}`:'Refresh from computer'],['Log fingerprint',String(d.id).split('-').pop()]];
 document.getElementById('diveInformation').innerHTML=`<h3 class="info-section-title">Dive computer</h3>${computerInfo.map(([label,value])=>`<div class="info-cell"><b>${esc(value)}</b>${esc(label)}</div>`).join('')}`;
 document.querySelectorAll('[data-dive-tab]').forEach(x=>x.classList.toggle('active',x.dataset.diveTab==='profile'));document.querySelectorAll('[data-dive-panel]').forEach(x=>x.classList.toggle('active',x.dataset.divePanel==='profile'));
 const decoCeiling=profile.map(p=>({t:+(p.t??p.time),ceil:+(p.stopDepth||0)})).filter(p=>Number.isFinite(p.t)&&Number.isFinite(p.ceil));
 const dlg=document.getElementById('profileDialog');dlg.showModal();requestAnimationFrame(()=>requestAnimationFrame(()=>drawDiveProfile('seaBirdsProfileCanvas',profile,{maxDepth:+d.depth,totalTime:+d.duration,isLight:true,ceilingWps:decoCeiling,showDecoCeiling:true})));
}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)go(nav.dataset.view);const gt=e.target.closest('[data-goto]');if(gt)go(gt.dataset.goto);const row=e.target.closest('.dive-row');if(row)openProfile(row.dataset.id);if(e.target.closest('.menu'))document.querySelector('.sidebar').classList.toggle('open')});
document.querySelectorAll('[data-dive-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-dive-tab]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('[data-dive-panel]').forEach(x=>x.classList.toggle('active',x.dataset.divePanel===button.dataset.diveTab))});
document.getElementById('diveEquipment').onclick=e=>{
 const d=state.dives.find(x=>x.id===activeDiveId);if(!d)return;
 const addCard=e.target.closest('#addGearCategory');
 if(addCard){const category=prompt('New equipment card name')?.trim();if(!category)return;const defaults=defaultGearLibrary(),library=state.gearLibrary||defaultGearLibrary();if([...Object.keys(defaults),...Object.keys(library)].some(name=>name.toLowerCase()===category.toLowerCase()))return toast('That equipment card already exists');state.gearLibrary=library;state.gearLibrary[category]=[];saveDiveEquipment(d,'Equipment card added');return}
 const add=e.target.closest('.add-gear-to-category');
 if(add){const category=add.dataset.category,name=prompt(`Equipment used from ${category}`)?.trim();if(!name)return;d.equipment=d.equipment||[];if(d.equipment.some(item=>item.toLowerCase()===name.toLowerCase()))return toast('This equipment is already on the dive');d.equipment.push(name);d.equipmentCategories={...(d.equipmentCategories||{}),[name]:category};state.gearLibrary=state.gearLibrary||defaultGearLibrary();state.gearLibrary[category]=state.gearLibrary[category]||[];if(!state.gearLibrary[category].some(item=>item.toLowerCase()===name.toLowerCase()))state.gearLibrary[category].push(name);saveDiveEquipment(d,'Equipment added');return}
 const remove=e.target.closest('.remove-dive-gear');
 if(remove){const item=remove.dataset.item;d.equipment=(d.equipment||[]).filter(name=>name!==item);if(d.equipmentCategories)delete d.equipmentCategories[item];saveDiveEquipment(d,'Equipment removed');return}
 const rename=e.target.closest('.rename-gear');
 if(rename){const original=rename.dataset.item,name=prompt('Rename equipment',original)?.trim();if(!name||name===original)return;if((d.equipment||[]).some(item=>item.toLowerCase()===name.toLowerCase()))return toast('This equipment is already on the dive');const index=(d.equipment||[]).indexOf(original);if(index<0)return;const library={...defaultGearLibrary(),...(state.gearLibrary||{})},category=d.equipmentCategories?.[original]||Object.keys(library).find(key=>(library[key]||[]).includes(original))||'Custom';d.equipment[index]=name;d.equipmentCategories={...(d.equipmentCategories||{})};delete d.equipmentCategories[original];d.equipmentCategories[name]=category;state.gearLibrary=state.gearLibrary||defaultGearLibrary();state.gearLibrary[category]=state.gearLibrary[category]||[];if(!state.gearLibrary[category].some(item=>item.toLowerCase()===name.toLowerCase()))state.gearLibrary[category].push(name);saveDiveEquipment(d,'Equipment renamed');return}
 const renameCard=e.target.closest('.rename-gear-category');
 if(renameCard){const original=renameCard.dataset.category,name=prompt('Rename equipment card',original)?.trim();if(!name||name===original)return;const allCategories=[...Object.keys(defaultGearLibrary()),...Object.keys(state.gearLibrary||{})];if(allCategories.some(category=>category.toLowerCase()===name.toLowerCase()))return toast('That equipment card already exists');state.gearLibrary=state.gearLibrary||defaultGearLibrary();state.gearLibrary[name]=state.gearLibrary[original]||[];delete state.gearLibrary[original];state.dives.forEach(dive=>{if(!dive.equipmentCategories)return;Object.keys(dive.equipmentCategories).forEach(item=>{if(dive.equipmentCategories[item]===original)dive.equipmentCategories[item]=name})});saveDiveEquipment(d,'Equipment card renamed');return}
 const removeCard=e.target.closest('.remove-gear-category');
 if(removeCard){const category=removeCard.dataset.category;if(!confirm(`Remove the "${category}" card? Its dive equipment will move to Custom.`))return;state.dives.forEach(dive=>{if(!dive.equipmentCategories)return;Object.keys(dive.equipmentCategories).forEach(item=>{if(dive.equipmentCategories[item]===category)dive.equipmentCategories[item]='Custom'})});state.gearLibrary=state.gearLibrary||defaultGearLibrary();delete state.gearLibrary[category];state.gearLibrary.Custom=state.gearLibrary.Custom||[];saveDiveEquipment(d,'Equipment card removed')}
};
document.getElementById('saveDiveDetails').onclick=()=>{const d=state.dives.find(x=>x.id===activeDiveId);if(!d)return;d.site=document.getElementById('editDiveTitle').value.trim()||d.site;d.location=document.getElementById('editDiveSpot').value.trim();d.buddy=document.getElementById('editDiveBuddy').value.trim();d.tags=document.getElementById('editDiveTags').value.split(',').map(x=>x.trim()).filter(Boolean);d.notes=document.getElementById('editDiveNotes').value.trim();d.userEdited=true;d.updatedAt=new Date().toISOString();persist();document.getElementById('profileDialog').close();toast('Dive details saved')};
document.getElementById('deleteDive').onclick=()=>{const d=state.dives.find(x=>x.id===activeDiveId);if(!d||!confirm(`Delete "${d.site}" from your logbook? It will stay excluded from future device downloads.`))return;state.deletedDiveIds=[...new Set([...(state.deletedDiveIds||[]),activeDiveId])];state.dives=state.dives.filter(x=>x.id!==activeDiveId);persist();document.getElementById('profileDialog').close();toast('Dive deleted')};
 let connectedComputer=null;
 const downloadDeviceDives=document.getElementById('downloadDeviceDives');
 document.querySelectorAll('.connect').forEach(b=>b.addEventListener('click',async()=>{const s=document.getElementById('deviceStatus'),label=s.querySelector('b'),detail=s.querySelector('p');try{b.disabled=true;downloadDeviceDives.hidden=true;document.getElementById('syncTimeOption').hidden=true;const selected=document.getElementById('deviceModel')?.value||'ble',isNative=!!window.Capacitor?.Plugins?.BluetoothLe,transport=selected==='perdix'&&!isNative?'serial':'ble';label.textContent=transport==='serial'?'Connecting to Perdix with Windows Bluetooth Classic…':'Connecting with Bluetooth Low Energy…';connectedComputer=await window.SeaBirdsShearwater.connectAndInspect(message=>{label.textContent=message;detail.textContent='Keep the dive computer on the Wait PC screen.'},transport);s.classList.add('connected');label.textContent=`${connectedComputer.name} · ${connectedComputer.logs} dive logs found`;detail.textContent=`Serial ${connectedComputer.serial||'unknown'} · firmware ${connectedComputer.firmware||'unknown'} · ready to download.`;downloadDeviceDives.textContent=`Download ${connectedComputer.logs} dives`;downloadDeviceDives.hidden=!connectedComputer.logs;document.getElementById('syncTimeOption').hidden=false;toast(`Found ${connectedComputer.logs} logs on ${connectedComputer.name}`)}catch(err){connectedComputer=null;downloadDeviceDives.hidden=true;document.getElementById('syncTimeOption').hidden=true;s.classList.remove('connected');label.textContent='Shearwater connection failed';detail.textContent=err.message||String(err);toast(err.message||String(err))}finally{b.disabled=false}}));
 downloadDeviceDives.onclick=async()=>{if(!connectedComputer)return;const s=document.getElementById('deviceStatus'),label=s.querySelector('b'),detail=s.querySelector('p');try{downloadDeviceDives.disabled=true;if(document.getElementById('syncDeviceTime').checked){label.textContent='Synchronizing dive computer time…';detail.textContent='Writing the current local date, time and timezone to the connected computer.';await connectedComputer.syncTime();detail.textContent='Dive computer time synchronized. Starting log download…'}const downloaded=await connectedComputer.downloadAll((current,total)=>{label.textContent=`Downloading dive ${current} of ${total}…`;detail.textContent='Keep the Perdix on the Wait PC screen until the transfer finishes.'});let added=0,updated=0;for(const dive of downloaded){if((state.deletedDiveIds||[]).includes(dive.id))continue;const index=state.dives.findIndex(d=>d.id===dive.id);if(index>=0){const old=state.dives[index],user=old.userEdited?{site:old.site,location:old.location,buddy:old.buddy,tags:old.tags,notes:old.notes,equipment:old.equipment,userEdited:true}:{};state.dives[index]={...dive,...user};updated++}else{state.dives.push(dive);added++}}persist();label.textContent=`Perdix dives synchronized`;detail.textContent=`${added} new dives added; ${updated} existing dives updated; ${(state.deletedDiveIds||[]).length} excluded.${document.getElementById('syncDeviceTime').checked?' Device time synchronized.':''}`;downloadDeviceDives.hidden=true;document.getElementById('syncTimeOption').hidden=true;go('dives');toast(`Imported ${added} new dives`)}catch(err){label.textContent='Dive download failed';detail.textContent=err.message||String(err);toast(err.message||String(err))}finally{downloadDeviceDives.disabled=false}};
const dd=document.getElementById('diveDialog');document.getElementById('addDive').onclick=()=>{dd.querySelector('[name=date]').value=new Date().toISOString().slice(0,10);dd.showModal()};dd.addEventListener('close',()=>{if(dd.returnValue!=='default')return;const f=new FormData(dd.querySelector('form')),depth=+f.get('depth'),duration=+f.get('duration');state.dives.push({id:crypto.randomUUID(),date:f.get('date'),site:f.get('site'),depth,duration,temp:f.get('temp')===''?null:+f.get('temp'),buddy:f.get('buddy'),notes:f.get('notes'),profile:sampleProfile(depth,duration),updatedAt:new Date().toISOString()});persist();toast('Dive saved')});
document.getElementById('search').oninput=filterRows;document.getElementById('sort').onchange=filterRows;
document.getElementById('depthUnit').onchange=e=>{state.settings.depth=e.target.value;window.units=e.target.value==='ft'?'imperial':'metric';persist()};document.getElementById('tempUnit').onchange=e=>{state.settings.temp=e.target.value;persist()};
document.getElementById('demoToggle').onchange=e=>{if(e.target.checked){state.dives=[...demo,...state.dives.filter(d=>!d.id.startsWith('demo-'))]}else state.dives=state.dives.filter(d=>!d.id.startsWith('demo-'));persist()};
document.getElementById('clearData').onclick=()=>{if(confirm('Delete all locally stored SeaBirds dives and reset device exclusions?')){state.dives=[];state.deletedDiveIds=[];persist();toast('Local log cleared')}};
document.getElementById('exportBtn').onclick=async()=>{const data=JSON.stringify(state,null,2),filename='seabirds-dive-log.json',bytes=new TextEncoder().encode(data).byteLength;if(window.SeaBirdsDesktop?.saveJson){try{const result=await window.SeaBirdsDesktop.saveJson(filename,data);if(!result.canceled)toast(`Exported ${(result.bytes/1048576).toFixed(2)} MB`)}catch(error){toast(`Export failed · ${error.message}`)}return}if(window.showSaveFilePicker){try{const handle=await window.showSaveFilePicker({suggestedName:filename,types:[{description:'JSON file',accept:{'application/json':['.json']}}]}),writable=await handle.createWritable();await writable.write(new Blob([data],{type:'application/json'}));await writable.close();toast(`Exported ${(bytes/1048576).toFixed(2)} MB`);return}catch(error){if(error.name==='AbortError')return;console.warn('Native browser save failed; using download fallback.',error)}}const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)};
document.getElementById('importFile').onchange=async e=>{const text=await e.target.files[0].text(),xml=new DOMParser().parseFromString(text,'application/xml'),nodes=[...xml.querySelectorAll('dive')];let n=0;for(const x of nodes){const get=(q)=>x.querySelector(q)?.textContent?.trim();const date=get('datetime')?.slice(0,10)||get('date')||new Date().toISOString().slice(0,10),depth=parseFloat(get('greatestdepth')||get('maxdepth')||0),duration=Math.round(parseFloat(get('divetime')||get('duration')||0)/60)||1;state.dives.push({id:crypto.randomUUID(),date,site:get('name')||get('divesite')||'Imported dive',depth,duration,temp:parseFloat(get('lowesttemperature'))||null,notes:'Imported from UDDF',profile:sampleProfile(depth,duration),updatedAt:new Date().toISOString()});n++}persist();toast(`Imported ${n} dives`)};
document.getElementById('googleSignIn').onclick=()=>window.SeaBirdsSync?.signIn().catch(e=>toast(e?.message||String(e)||'Google sign-in failed'));
window.SeaBirdsApp={getState:()=>JSON.parse(JSON.stringify(state)),applyRemote:s=>{state=s;localStorage.setItem(KEY,JSON.stringify(state));render()},setSyncStatus:s=>{document.getElementById('syncStatus').textContent=s.text;document.getElementById('googleSignIn').textContent=s.signedIn?'Sign out':'Sign in with Google';document.getElementById('storageMode').textContent=s.signedIn?'Cloud sync':'Local-first';document.getElementById('storageDetail').textContent=s.signedIn?s.text:'Sign in to sync across devices'}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();window.SeaBirdsSync?.init();
})();
