(function(){
'use strict';
const KEY='seabirds_state_v1';
window.units='metric';
window._lspCssVar=(name,fallback)=>getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback;
const sampleProfile=(depth,duration)=>[{t:0,depth:0,type:'surface'},{t:2,depth,type:'descent'},{t:Math.max(3,duration-5),depth,type:'bottom'},{t:duration-2,depth:5,type:'ascent'},{t:duration,depth:0,type:'surface'}];
const demo=[
 {id:'demo-1',date:'2026-07-28',site:'Blue Corner',location:'Palau',depth:31.8,duration:52,temp:28,buddy:'Maya',notes:'Strong current, grey reef sharks.',profile:sampleProfile(31.8,52),updatedAt:new Date().toISOString()},
 {id:'demo-2',date:'2026-07-26',site:'German Channel',location:'Palau',depth:24.3,duration:61,temp:28,buddy:'Maya',notes:'Manta cleaning station.',profile:sampleProfile(24.3,61),updatedAt:new Date().toISOString()},
 {id:'demo-3',date:'2026-06-15',site:'USS Liberty',location:'Tulamben, Bali',depth:27.1,duration:48,temp:27,buddy:'Ken',notes:'Early morning wreck dive.',profile:sampleProfile(27.1,48),updatedAt:new Date().toISOString()}];
let state=load();
function load(){try{return Object.assign({dives:[],settings:{depth:'m',temp:'c'},revision:0,updatedAt:''},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {dives:[],settings:{depth:'m',temp:'c'},revision:0,updatedAt:''}}}
function persist(sync=true){state.updatedAt=new Date().toISOString();state.revision=(state.revision||0)+1;localStorage.setItem(KEY,JSON.stringify(state));if(sync&&window.SeaBirdsSync)window.SeaBirdsSync.queue(state);render()}
function esc(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML}
function converted(d){return state.settings.depth==='ft'?(d*3.28084):d}
function temp(t){return state.settings.temp==='f'?(t*9/5+32):t}
function fmtDate(s){const d=new Date(s+'T12:00:00');return {day:d.getDate(),month:d.toLocaleDateString(undefined,{month:'short'}).toUpperCase(),full:d.toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})}}
function rows(target,dives){target.innerHTML=dives.length?dives.map(d=>{const x=fmtDate(d.date);return `<button class="dive-row" data-id="${esc(d.id)}"><span class="date-tile"><b>${x.day}</b><small>${x.month}</small></span><span class="site"><b>${esc(d.site)}</b><small>${esc(d.location||d.buddy||'Dive')}</small></span><span class="metric"><b>${converted(+d.depth).toFixed(1)} ${state.settings.depth}</b><small>Max depth</small></span><span class="metric"><b>${d.duration} min</b><small>Bottom time</small></span><span class="metric"><b>${d.temp==null?'—':temp(+d.temp).toFixed(0)+'°'+state.settings.temp.toUpperCase()}</b><small>Water</small></span><span>›</span></button>`}).join(''):`<div class="empty"><b>No dives yet</b>Connect your Shearwater or add a dive manually.</div>`}
function render(){
 const dives=[...state.dives].sort((a,b)=>b.date.localeCompare(a.date));
 document.getElementById('diveCount').textContent=dives.length;document.getElementById('statDives').textContent=dives.length;
 const mins=dives.reduce((n,d)=>n+(+d.duration||0),0);document.getElementById('statTime').innerHTML=(mins/60).toFixed(mins>=600?0:1)+'<sup>h</sup>';
 const md=Math.max(0,...dives.map(d=>+d.depth||0));document.getElementById('statDepth').textContent=dives.length?converted(md).toFixed(1)+' '+state.settings.depth:'—';
 const ts=dives.filter(d=>d.temp!=null);document.getElementById('statTemp').textContent=ts.length?(ts.reduce((n,d)=>n+temp(+d.temp),0)/ts.length).toFixed(1)+'°'+state.settings.temp.toUpperCase():'—';
 rows(document.getElementById('recentDives'),dives.slice(0,4));filterRows();
 document.getElementById('depthUnit').value=state.settings.depth;document.getElementById('tempUnit').value=state.settings.temp;
}
function filterRows(){let ds=[...state.dives],q=(document.getElementById('search').value||'').toLowerCase(),sort=document.getElementById('sort').value;if(q)ds=ds.filter(d=>JSON.stringify(d).toLowerCase().includes(q));ds.sort(sort==='date-asc'?(a,b)=>a.date.localeCompare(b.date):sort==='depth-desc'?(a,b)=>b.depth-a.depth:(a,b)=>b.date.localeCompare(a.date));rows(document.getElementById('allDives'),ds)}
function go(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===id));document.getElementById('viewName').textContent=({dashboard:'Overview',dives:'Dive log',devices:'Devices',settings:'Settings'})[id];document.querySelector('.sidebar').classList.remove('open')}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function drawTemperatureProfile(profile){const canvas=document.getElementById('temperatureProfileCanvas'),rect=canvas.getBoundingClientRect(),ratio=devicePixelRatio||1;canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const points=profile.map(p=>({t:p.t,v:p.temperature??p.temp})).filter(p=>Number.isFinite(p.v));if(points.length<2){canvas.hidden=true;return}canvas.hidden=false;const W=rect.width,H=rect.height,pad={l:42,r:10,t:10,b:18},min=Math.floor(Math.min(...points.map(p=>p.v))-1),max=Math.ceil(Math.max(...points.map(p=>p.v))+1),end=Math.max(...points.map(p=>p.t));ctx.fillStyle='#f4f7f5';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#d7e1df';ctx.beginPath();ctx.moveTo(pad.l,pad.t);ctx.lineTo(pad.l,H-pad.b);ctx.lineTo(W-pad.r,H-pad.b);ctx.stroke();ctx.strokeStyle='#596cff';ctx.lineWidth=2;ctx.beginPath();points.forEach((p,i)=>{const x=pad.l+p.t/end*(W-pad.l-pad.r),y=pad.t+(max-p.v)/(max-min)*(H-pad.t-pad.b);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#52656c';ctx.font='10px sans-serif';ctx.fillText(`${max}°C`,4,pad.t+4);ctx.fillText(`${min}°C`,4,H-pad.b);ctx.fillText('Water temperature',pad.l+5,14)}
function openProfile(id){const d=state.dives.find(x=>x.id===id);if(!d)return;document.getElementById('profileTitle').textContent=d.site+' · '+fmtDate(d.date).full;const profile=d.profile?.length?d.profile.map(p=>({...p,t:p.t??p.time})):sampleProfile(+d.depth,+d.duration),temps=profile.map(p=>p.temperature??p.temp).filter(Number.isFinite),tts=profile.map(p=>p.tts).filter(Number.isFinite),gases=[...new Set(profile.map(p=>p.gas).filter(Boolean))],hasTelemetry=profile.some(p=>p.ndl!=null||p.tts!=null||p.gas||p.gfLow!=null);document.getElementById('telemetryNotice').hidden=hasTelemetry||!String(d.id).startsWith('shearwater-');document.getElementById('profileStats').innerHTML=`<span><b>${converted(+d.depth).toFixed(1)} ${state.settings.depth}</b>Maximum depth</span><span><b>${d.duration} min</b>Dive time</span><span><b>${temps.length?temp(Math.min(...temps)).toFixed(1)+'°'+state.settings.temp.toUpperCase():'—'}</b>Minimum water temp</span><span><b>${d.avgDepth?converted(d.avgDepth).toFixed(1)+' '+state.settings.depth:'—'}</b>Mean depth</span><span><b>${tts.length?Math.max(...tts)+' min':'—'}</b>Maximum TTS</span><span><b>${gases.length?gases.join(' · '):'—'}</b>Gas O₂/He</span><span><b>${d.gfLow!=null?d.gfLow+'/'+d.gfHigh:'—'}</b>Device GF</span>`;const dlg=document.getElementById('profileDialog');dlg.showModal();requestAnimationFrame(()=>requestAnimationFrame(()=>{drawDiveProfile('seaBirdsProfileCanvas',profile,{maxDepth:+d.depth,totalTime:+d.duration,isLight:true});drawTemperatureProfile(profile)}));}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)go(nav.dataset.view);const gt=e.target.closest('[data-goto]');if(gt)go(gt.dataset.goto);const row=e.target.closest('.dive-row');if(row)openProfile(row.dataset.id);if(e.target.closest('.menu'))document.querySelector('.sidebar').classList.toggle('open')});
 let connectedComputer=null;
 const downloadDeviceDives=document.getElementById('downloadDeviceDives');
 document.querySelectorAll('.connect').forEach(b=>b.addEventListener('click',async()=>{const s=document.getElementById('deviceStatus'),label=s.querySelector('b'),detail=s.querySelector('p');try{b.disabled=true;downloadDeviceDives.hidden=true;connectedComputer=await window.SeaBirdsShearwater.connectAndInspect(message=>{label.textContent=message;detail.textContent='Keep the dive computer on the Wait PC screen.'},b.dataset.transport||'ble');s.classList.add('connected');label.textContent=`${connectedComputer.name} · ${connectedComputer.logs} dive logs found`;detail.textContent=`Serial ${connectedComputer.serial||'unknown'} · firmware ${connectedComputer.firmware||'unknown'} · ready to download.`;downloadDeviceDives.textContent=`Download ${connectedComputer.logs} dives`;downloadDeviceDives.hidden=!connectedComputer.logs;toast(`Found ${connectedComputer.logs} logs on ${connectedComputer.name}`)}catch(err){connectedComputer=null;downloadDeviceDives.hidden=true;s.classList.remove('connected');label.textContent='Shearwater connection failed';detail.textContent=err.message||String(err);toast(err.message||String(err))}finally{b.disabled=false}}));
 downloadDeviceDives.onclick=async()=>{if(!connectedComputer)return;const s=document.getElementById('deviceStatus'),label=s.querySelector('b'),detail=s.querySelector('p');try{downloadDeviceDives.disabled=true;const downloaded=await connectedComputer.downloadAll((current,total)=>{label.textContent=`Downloading dive ${current} of ${total}…`;detail.textContent='Keep the Perdix on the Wait PC screen until the transfer finishes.'});let added=0;for(const dive of downloaded){const index=state.dives.findIndex(d=>d.id===dive.id);if(index>=0)state.dives[index]=dive;else{state.dives.push(dive);added++}}persist();label.textContent=`${downloaded.length} Perdix dives downloaded`;detail.textContent=`${added} new dives added; ${downloaded.length-added} existing dives updated.`;downloadDeviceDives.hidden=true;go('dives');toast(`Imported ${added} new dives`)}catch(err){label.textContent='Dive download failed';detail.textContent=err.message||String(err);toast(err.message||String(err))}finally{downloadDeviceDives.disabled=false}};
const dd=document.getElementById('diveDialog');document.getElementById('addDive').onclick=()=>{dd.querySelector('[name=date]').value=new Date().toISOString().slice(0,10);dd.showModal()};dd.addEventListener('close',()=>{if(dd.returnValue!=='default')return;const f=new FormData(dd.querySelector('form')),depth=+f.get('depth'),duration=+f.get('duration');state.dives.push({id:crypto.randomUUID(),date:f.get('date'),site:f.get('site'),depth,duration,temp:f.get('temp')===''?null:+f.get('temp'),buddy:f.get('buddy'),notes:f.get('notes'),profile:sampleProfile(depth,duration),updatedAt:new Date().toISOString()});persist();toast('Dive saved')});
document.getElementById('search').oninput=filterRows;document.getElementById('sort').onchange=filterRows;
document.getElementById('depthUnit').onchange=e=>{state.settings.depth=e.target.value;window.units=e.target.value==='ft'?'imperial':'metric';persist()};document.getElementById('tempUnit').onchange=e=>{state.settings.temp=e.target.value;persist()};
document.getElementById('demoToggle').onchange=e=>{if(e.target.checked){state.dives=[...demo,...state.dives.filter(d=>!d.id.startsWith('demo-'))]}else state.dives=state.dives.filter(d=>!d.id.startsWith('demo-'));persist()};
document.getElementById('clearData').onclick=()=>{if(confirm('Delete all locally stored SeaBirds dives?')){state.dives=[];persist();toast('Local log cleared')}};
document.getElementById('exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='seabirds-dive-log.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('importFile').onchange=async e=>{const text=await e.target.files[0].text(),xml=new DOMParser().parseFromString(text,'application/xml'),nodes=[...xml.querySelectorAll('dive')];let n=0;for(const x of nodes){const get=(q)=>x.querySelector(q)?.textContent?.trim();const date=get('datetime')?.slice(0,10)||get('date')||new Date().toISOString().slice(0,10),depth=parseFloat(get('greatestdepth')||get('maxdepth')||0),duration=Math.round(parseFloat(get('divetime')||get('duration')||0)/60)||1;state.dives.push({id:crypto.randomUUID(),date,site:get('name')||get('divesite')||'Imported dive',depth,duration,temp:parseFloat(get('lowesttemperature'))||null,notes:'Imported from UDDF',profile:sampleProfile(depth,duration),updatedAt:new Date().toISOString()});n++}persist();toast(`Imported ${n} dives`)};
document.getElementById('googleSignIn').onclick=()=>window.SeaBirdsSync?.signIn().catch(e=>toast(e.message));
window.SeaBirdsApp={getState:()=>JSON.parse(JSON.stringify(state)),applyRemote:s=>{state=s;localStorage.setItem(KEY,JSON.stringify(state));render()},setSyncStatus:s=>{document.getElementById('syncStatus').textContent=s.text;document.getElementById('googleSignIn').textContent=s.signedIn?'Sign out':'Sign in with Google'}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();window.SeaBirdsSync?.init();
})();
