(function(){
'use strict';
const NS=window.SeaBirds=window.SeaBirds||{},Core=NS.Core;
let deviceFilters=new Set(),modeFilters=new Set(),styleFilters=new Set();
const source=d=>{if(!d.computer&&!d.computerModel&&!String(d.id||'').startsWith('shearwater-'))return'Manual entry';const raw=String(d.computer||d.computerModel||'Shearwater').replace(/^Shearwater\s+/i,'').trim(),known={'perdix':'Perdix','perdix ai':'Perdix AI','perdix 2':'Perdix 2','teric':'Teric','petrel 2':'Petrel 2','petrel 3':'Petrel 3','nerd 2':'NERD 2','peregrine':'Peregrine','tern':'Tern'};return known[raw.toLowerCase()]||raw||'Shearwater'};
const mode=d=>d.diveMode||((d.profile||[]).some(point=>point.setpoint!=null)?'CCR':'OC');
const style=d=>d.diveStyle||'Not specified';
const stamp=d=>`${d.date||''}T${d.time||'00:00'}`;
function displayTime(value){if(!value)return'';const [hours,minutes]=value.split(':').map(Number);if(Core.getState().settings.timeFormat==='24')return`${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}`;return`${hours%12||12}:${String(minutes).padStart(2,'0')} ${hours>=12?'PM':'AM'}`}
function rows(target,dives){if(!target)return;const state=Core.getState();target.innerHTML=dives.length?dives.map(d=>{const date=Core.formatDate(d.date),subtitle=d.location||d.buddy||'',diveMode=mode(d),diveStyle=style(d),classification=diveStyle==='Not specified'?diveMode:`${diveMode} / ${diveStyle}`,time=displayTime(d.time);return`<button class="dive-row" data-id="${Core.esc(d.id)}"><span class="dive-number-cell"><small>Dive #</small><b>${d.diveNumber??'—'}</b></span><span class="date-tile full-date"><b>${date.ymd}</b>${time?`<small>${Core.esc(time)}</small>`:''}</span><span class="site"><span class="dive-title-line"><b>${Core.esc(d.site)}</b></span><span class="dive-card-details"><em>${Core.esc(classification)}</em><span>${Core.converted(+d.depth).toFixed(1)} ${state.settings.depth}</span><span>${d.duration} min</span><span class="card-temperature">${d.temp==null?'—':Core.temperature(+d.temp).toFixed(0)+'°'+state.settings.temp.toUpperCase()}</span></span>${subtitle?`<small>${Core.esc(subtitle)}</small>`:''}</span><span class="dive-row-arrow">›</span></button>`}).join(''):'<div class="empty"><b>No dives found</b>Change the search or filters to show more dives.</div>'}
function sources(){return[...new Set(Core.getState().dives.map(source))].sort((a,b)=>a==='Manual entry'?1:b==='Manual entry'?-1:a.localeCompare(b))}
function renderGroup(id,label,attribute,available,selected){const target=document.getElementById(id);if(!target)return selected;const valid=new Set(available);selected=new Set([...selected].filter(item=>valid.has(item)));target.innerHTML=`<span>${label}:</span><label><input type="checkbox" data-${attribute}="all" ${selected.size?'':'checked'}> All</label>${available.map(item=>`<label><input type="checkbox" data-${attribute}="${Core.esc(item)}" ${selected.has(item)?'checked':''}> ${Core.esc(item)}</label>`).join('')}`;return selected}
function renderFilters(){const dives=Core.getState().dives;deviceFilters=renderGroup('deviceFilters','Computer','device-filter',sources(),deviceFilters);modeFilters=renderGroup('modeFilters','Mode','mode-filter',[...new Set(dives.map(mode))].sort(),modeFilters);styleFilters=renderGroup('styleFilters','Style','style-filter',[...new Set(dives.map(style))].sort((a,b)=>a==='Not specified'?1:b==='Not specified'?-1:a.localeCompare(b)),styleFilters)}
function filterRows(){const state=Core.getState();let dives=[...state.dives],q=(document.getElementById('search')?.value||'').toLowerCase(),sort=document.getElementById('sort')?.value;if(q)dives=dives.filter(d=>JSON.stringify(d).toLowerCase().includes(q));if(deviceFilters.size)dives=dives.filter(d=>deviceFilters.has(source(d)));if(modeFilters.size)dives=dives.filter(d=>modeFilters.has(mode(d)));if(styleFilters.size)dives=dives.filter(d=>styleFilters.has(style(d)));dives.sort(sort==='date-asc'?(a,b)=>stamp(a).localeCompare(stamp(b)):sort==='depth-desc'?(a,b)=>b.depth-a.depth:(a,b)=>stamp(b).localeCompare(stamp(a)));rows(document.getElementById('allDives'),dives)}
function render(){const state=Core.getState(),dives=[...state.dives].sort((a,b)=>stamp(b).localeCompare(stamp(a)));document.getElementById('diveCount').textContent=dives.length;document.getElementById('statDives').textContent=dives.length;const mins=dives.reduce((n,d)=>n+(+d.duration||0),0);document.getElementById('statTime').innerHTML=(mins/60).toFixed(mins>=600?0:1)+'<sup>h</sup>';const depth=Math.max(0,...dives.map(d=>+d.depth||0));document.getElementById('statDepth').textContent=dives.length?Core.converted(depth).toFixed(1)+' '+state.settings.depth:'—';const longest=Math.round(Math.max(0,...dives.map(d=>+d.duration||0))),hours=Math.floor(longest/60),remainder=longest%60;document.getElementById('statLongest').textContent=dives.length?(hours?`${hours}h ${remainder}min`:`${remainder}min`):'—';rows(document.getElementById('recentDives'),dives.slice(0,4));renderFilters();filterRows()}
function bindFilter(id,attribute,getSet,setSet){document.getElementById(id).onchange=event=>{const input=event.target.closest(`[data-${attribute}]`);if(!input)return;const value=input.dataset[attribute.replace(/-([a-z])/g,(_,letter)=>letter.toUpperCase())],selected=getSet();if(value==='all')selected.clear();else input.checked?selected.add(value):selected.delete(value);setSet(selected);renderFilters();filterRows()}}
function init(){Core.registerRenderer(render);document.getElementById('search').oninput=filterRows;document.getElementById('sort').onchange=filterRows;bindFilter('deviceFilters','device-filter',()=>deviceFilters,value=>deviceFilters=value);bindFilter('modeFilters','mode-filter',()=>modeFilters,value=>modeFilters=value);bindFilter('styleFilters','style-filter',()=>styleFilters,value=>styleFilters=value);document.addEventListener('click',event=>{const row=event.target.closest('.dive-row');if(row)Core.feature('diveEditor')?.open(row.dataset.id)})}
Core.registerFeature('diveList',{init,render,filterRows,source});
})();
