(function(){
'use strict';
const NS=window.SeaBirds=window.SeaBirds||{},Core=NS.Core;
function render(){const state=Core.getState();[['depthUnit','depth'],['tempUnit','temp'],['volumeUnit','volume'],['weightUnit','weight'],['pressureUnit','pressure'],['dateFormat','dateFormat'],['timeFormat','timeFormat']].forEach(([id,key])=>{const node=document.getElementById(id);if(node)node.value=state.settings[key]});Core.feature('equipment')?.renderMaster()}
function showMasterGear(show){const main=document.getElementById('settingsMain'),page=document.getElementById('masterGearPage'),viewName=document.getElementById('viewName');if(!main||!page)return;main.hidden=show;page.hidden=!show;if(viewName)viewName.textContent=show?'Equipment lists':'Settings';if(show)Core.feature('equipment')?.renderMaster();window.scrollTo({top:0,behavior:'smooth'})}
function bindMaster(){document.querySelector('.master-gear').onclick=async event=>{const addCard=event.target.closest('#addMasterGearCard'),addItem=event.target.closest('.add-master-item'),renameCard=event.target.closest('.rename-master-card'),removeCard=event.target.closest('.remove-master-card'),renameItem=event.target.closest('.rename-master-item'),removeItem=event.target.closest('.remove-master-item');if(!addCard&&!addItem&&!renameCard&&!removeCard&&!renameItem&&!removeItem)return;await Core.commit(state=>{const library=state.gearLibrary=state.gearLibrary||Core.defaultGearLibrary();if(addCard){const name=prompt('New equipment list name (for example: Photo dive)')?.trim();if(name)library[name]=library[name]||[]}else if(addItem){const name=prompt(`Add equipment to ${addItem.dataset.category}`)?.trim();if(name)library[addItem.dataset.category]=[...new Set([...(library[addItem.dataset.category]||[]),name])]}else if(renameCard){const original=renameCard.dataset.category,name=prompt('Rename master equipment list',original)?.trim();if(name&&name!==original){library[name]=library[original];delete library[original]}}else if(removeCard){if(confirm(`Delete the master list "${removeCard.dataset.category}"? Existing dives will not be changed.`))delete library[removeCard.dataset.category]}else if(renameItem){const category=renameItem.dataset.category,original=renameItem.dataset.item,name=prompt('Rename master equipment item',original)?.trim();if(name)library[category]=library[category].map(item=>item===original?name:item)}else if(removeItem&&confirm(`Delete "${removeItem.dataset.item}" from the ${removeItem.dataset.category} master list?`))library[removeItem.dataset.category]=(library[removeItem.dataset.category]||[]).filter(item=>item!==removeItem.dataset.item)},{sync:false});Core.notify('Master list changed · Save to sync')};document.getElementById('saveMasterGear').onclick=()=>Core.commit(()=>{}).then(()=>Core.notify('Master equipment lists saved'))}
function init(){Core.registerRenderer(render);[['depthUnit','depth'],['tempUnit','temp'],['volumeUnit','volume'],['weightUnit','weight'],['pressureUnit','pressure'],['dateFormat','dateFormat'],['timeFormat','timeFormat']].forEach(([id,key])=>document.getElementById(id).onchange=event=>Core.commit(state=>{state.settings[key]=event.target.value;if(key==='depth')window.units=event.target.value==='ft'?'imperial':'metric'}));document.getElementById('demoToggle').onchange=event=>Core.commit(state=>{state.dives=event.target.checked?[...Core.demo,...state.dives.filter(d=>!d.id.startsWith('demo-'))]:state.dives.filter(d=>!d.id.startsWith('demo-'))});document.getElementById('clearData').onclick=()=>{if(confirm('Delete all locally stored SeaBirds dives and reset device exclusions?'))Core.commit(state=>{state.dives=[];state.deletedDiveIds=[]}).then(()=>Core.notify('Local log cleared'))};document.getElementById('googleSignIn').onclick=()=>window.SeaBirdsSync?.signIn().catch(error=>Core.notify(error?.message||String(error)||'Google sign-in failed'));document.getElementById('openMasterGear').onclick=()=>showMasterGear(true);document.getElementById('closeMasterGear').onclick=()=>showMasterGear(false);document.querySelector('.nav[data-view="settings"]').addEventListener('click',()=>showMasterGear(false));bindMaster()}
Core.registerFeature('settings',{init,render,showMasterGear});
})();
